In [1]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import regularizers
import xgboost as xgb
from sklearn.decomposition import PCA
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import RobustScaler, LabelEncoder, StandardScaler # Import LabelEncoder and StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
pd.set_option('display.max_columns',None)
warnings.filterwarnings('ignore')
%matplotlib inline

KeyboardInterrupt:

In [ ]:
data_train = pd.read_csv("KDDTrain+.txt", header=None)

columns = (['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot'
,'num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations'
,'num_shells','num_access_files','num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate'
,'srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count'
,'dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate'
,'dst_host_srv_serror_rate','dst_host_rerror_rate','dst_host_srv_rerror_rate','outcome','level'])
data_train.columns = columns

In [ ]:
data_train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,outcome,level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [29]:
columns = (['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot'
,'num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations'
,'num_shells','num_access_files','num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate'
,'srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count'
,'dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate'
,'dst_host_srv_serror_rate','dst_host_rerror_rate','dst_host_srv_rerror_rate','outcome','level'])

In [30]:
data_train.columns = columns

In [31]:
data_train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,outcome,level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123,6,1.0,1.0,0.0,0.0,0.05,0.07,0.00,255,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [32]:
attack_mapping = {
    'normal': 'normal',
    'neptune': 'DoS',
    'smurf': 'DoS',
    'back': 'DoS',
    'teardrop': 'DoS',
    'pod': 'DoS',
    'land': 'DoS',
    'apache2': 'DoS',
    'mailbomb': 'DoS',
    'processtable': 'DoS',
    'udpstorm': 'DoS',
    'nuked': 'DoS',
    'worm': 'DoS',

    'ipsweep': 'Probe',
    'portsweep': 'Probe',
    'nmap': 'Probe',
    'satan': 'Probe',
    'mscan': 'Probe',
    'saint': 'Probe',
    'xsnoop': 'Probe',
    'snmpgetattack': 'Probe',
    'snmpguess': 'Probe',
    'httptunnel': 'Probe',

    'warezclient': 'R2L',
    'guess_passwd': 'R2L',
    'ftp_write': 'R2L',
    'multihop': 'R2L',
    'imap': 'R2L',
    'warezmaster': 'R2L',
    'phf': 'R2L',
    'spy': 'R2L',
    'sendmail': 'R2L',
    'secrect': 'R2L',

    'rootkit': 'U2R',
    'buffer_overflow': 'U2R',
    'loadmodule': 'U2R',
    'perl': 'U2R',
    'ps': 'U2R',
    'sqlattack': 'U2R',
    'xterm': 'U2R',
    'named': 'U2R',
    'xlock': 'U2R'
}

unmapped_attacks = set(data_train['outcome'].unique()) - set(attack_mapping.keys())
if unmapped_attacks:
    print(f"Warning: The following attack types in 'outcome' are not in the provided mapping: {unmapped_attacks}. They will be mapped to 'Other_Attack'.")
    for attack in unmapped_attacks:
        attack_mapping[attack] = 'Other_Attack'

data_train['attack_class'] = data_train['outcome'].map(attack_mapping)

print("\nValue counts for 'attack_class' after mapping:")
print(data_train['attack_class'].value_counts())

Value counts for 'attack_class' after mapping:
attack_class
normal    67343
DoS       45927
Probe     11656
R2L         995
U2R          52
Name: count, dtype: int64

In [55]:
data_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 44 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     125973 non-null  int64
 1   protocol_type                125973 non-null  str
 2   service                      125973 non-null  str
 3   flag                         125973 non-null  str
 4   src_bytes                    125973 non-null  int64
 5   dst_bytes                    125973 non-null  int64
 6   land                         125973 non-null  int64
 7   wrong_fragment               125973 non-null  int64
 8   urgent                       125973 non-null  int64
 9   hot                          125973 non-null  int64
 10  num_failed_logins            125973 non-null  int64
 11  logged_in                    125973 non-null  int64
 12  num_compromised              125973 non-null  int64
 13  root_shell                   125973 non-null  int64
 14  su_attempted                 125973 non-null  int64
 15  num_root                     125973 non-null  int64
 16  num_file_creations           125973 non-null  int64
 17  num_shells                   125973 non-null  int64
 18  num_access_files             125973 non-null  int64
 19  num_outbound_cmds            125973 non-null  int64
 20  is_host_login                125973 non-null  int64
 21  is_guest_login               125973 non-null  int64
 22  count                        125973 non-null  int64
 23  srv_count                    125973 non-null  int64
 24  serror_rate                  125973 non-null  float64
 25  srv_serror_rate              125973 non-null  float64
 26  rerror_rate                  125973 non-null  float64
 27  srv_rerror_rate              125973 non-null  float64
 28  same_srv_rate                125973 non-null  float64
 29  diff_srv_rate                125973 non-null  float64
 30  srv_diff_host_rate           125973 non-null  float64
 31  dst_host_count               125973 non-null  int64
 32  dst_host_srv_count           125973 non-null  int64
 33  dst_host_same_srv_rate       125973 non-null  float64
 34  dst_host_diff_srv_rate       125973 non-null  float64
 35  dst_host_same_src_port_rate  125973 non-null  float64
 36  dst_host_srv_diff_host_rate  125973 non-null  float64
 37  dst_host_serror_rate         125973 non-null  float64
 38  dst_host_srv_serror_rate     125973 non-null  float64
 39  dst_host_rerror_rate         125973 non-null  float64
 40  dst_host_srv_rerror_rate     125973 non-null  float64
 41  outcome                      125973 non-null  str
 42  level                        125973 non-null  int64
 43  attack_class                 125973 non-null  str
dtypes: float64(15), int64(24), str(5)
memory usage: 42.3 MB

In [56]:
data_train.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,level
count,125973.00000,1.259730e+05,1.259730e+05,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.0,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000
mean,287.14465,4.556674e+04,1.977911e+04,0.000198,0.022687,0.000111,0.204409,0.001222,0.395736,0.279250,0.001342,0.001103,0.302192,0.012669,0.000413,0.004096,0.0,0.000008,0.009423,84.107555,27.737888,0.284485,0.282485,0.119958,0.121183,0.660928,0.063053,0.097322,182.148945,115.653005,0.521242,0.082951,0.148379,0.032542,0.284452,0.278485,0.118832,0.120240,19.504060
std,2604.51531,5.870331e+06,4.021269e+06,0.014086,0.253530,0.014366,2.149968,0.045239,0.489010,23.942042,0.036603,0.045154,24.399618,0.483935,0.022181,0.099370,0.0,0.002817,0.096612,114.508607,72.635840,0.446456,0.447022,0.320436,0.323647,0.439623,0.180314,0.259830,99.206213,110.702741,0.448949,0.188922,0.308997,0.112564,0.444784,0.445669,0.306557,0.319459,2.291503
min,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.090000,0.000000,0.000000,82.000000,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000
50%,0.00000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,14.000000,8.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,255.000000,63.000000,0.510000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000
75%,0.00000,2.760000e+02,5.160000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,143.000000,18.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.060000,0.000000,255.000000,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000,21.000000
max,42908.00000,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,77.000000,5.000000,1.000000,7479.000000,1.000000,2.000000,7468.000000,43.000000,2.000000,9.000000,0.0,1.000000,1.000000,511.000000,511.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,255.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,21.000000

In [57]:
def pie_plot(df, cols_list, rows, cols):
    fig, axes = plt.subplots(rows, cols)
    for ax, col in zip(axes.ravel(), cols_list):
        df[col].value_counts().plot(ax=ax, kind='pie', figsize=(15, 15), fontsize=10, autopct='%1.0f%%')
        ax.set_title(str(col), fontsize = 12)
    plt.show()

In [58]:
print("Unique values for 'num_outbound_cmds':", data_train['num_outbound_cmds'].unique())
print("Unique values for 'land':", data_train['land'].unique())
print("Unique values for 'urgent':", data_train['urgent'].unique())

data_train_cleaned = data_train.drop(columns=['num_outbound_cmds', 'land', 'urgent','level'])

print(f"Original number of columns: {data_train.shape[1]}")
print(f"Number of columns after dropping irrelevant features: {data_train_cleaned.shape[1]}")

Unique values for 'num_outbound_cmds': [0]
Unique values for 'land': [0 1]
Unique values for 'urgent': [0 1 3 2]
Original number of columns: 44
Number of columns after dropping irrelevant features: 40

In [59]:
corr_matrix = data_train_cleaned.corr(numeric_only=True).abs()
upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
print("Highly correlated features:")
print(to_drop)
data_train_final = data_train_cleaned.drop(columns=to_drop)
data_train_final.drop(columns=['outcome'], inplace=True)

Highly correlated features:
['num_root', 'srv_serror_rate', 'srv_rerror_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_srv_rerror_rate']

In [60]:
data_train_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     125973 non-null  int64
 1   protocol_type                125973 non-null  str
 2   service                      125973 non-null  str
 3   flag                         125973 non-null  str
 4   src_bytes                    125973 non-null  int64
 5   dst_bytes                    125973 non-null  int64
 6   wrong_fragment               125973 non-null  int64
 7   hot                          125973 non-null  int64
 8   num_failed_logins            125973 non-null  int64
 9   logged_in                    125973 non-null  int64
 10  num_compromised              125973 non-null  int64
 11  root_shell                   125973 non-null  int64
 12  su_attempted                 125973 non-null  int64
 13  num_file_creations           125973 non-null  int64
 14  num_shells                   125973 non-null  int64
 15  num_access_files             125973 non-null  int64
 16  is_host_login                125973 non-null  int64
 17  is_guest_login               125973 non-null  int64
 18  count                        125973 non-null  int64
 19  srv_count                    125973 non-null  int64
 20  serror_rate                  125973 non-null  float64
 21  rerror_rate                  125973 non-null  float64
 22  same_srv_rate                125973 non-null  float64
 23  diff_srv_rate                125973 non-null  float64
 24  srv_diff_host_rate           125973 non-null  float64
 25  dst_host_count               125973 non-null  int64
 26  dst_host_srv_count           125973 non-null  int64
 27  dst_host_same_srv_rate       125973 non-null  float64
 28  dst_host_diff_srv_rate       125973 non-null  float64
 29  dst_host_same_src_port_rate  125973 non-null  float64
 30  dst_host_srv_diff_host_rate  125973 non-null  float64
 31  dst_host_rerror_rate         125973 non-null  float64
 32  attack_class                 125973 non-null  str
dtypes: float64(10), int64(19), str(4)
memory usage: 31.7 MB

In [40]:
def Scaling(df_num, cols):
    std_scaler = RobustScaler()
    std_scaler_temp = std_scaler.fit_transform(df_num)
    std_df = pd.DataFrame(std_scaler_temp, columns =cols)
    return std_df

In [61]:
data_train_final = pd.get_dummies(
    data_train_final,
    columns=['protocol_type', 'service', 'flag'],
    drop_first=True
)

In [64]:
data_train_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Columns: 111 entries, duration to flag_SH
dtypes: bool(81), float64(10), int64(20)
memory usage: 38.6 MB

In [63]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data_train_final['attack_class'] = le.fit_transform(data_train_final['attack_class'])

In [65]:
X = data_train_final.drop('attack_class', axis=1)
y = data_train_final['attack_class']

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
# Split first
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Scale after split
scaler = RobustScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=10,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='multi:softmax',
    num_class=len(set(y_train)),
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1, num_class=5, ...)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=25,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

RandomForestClassifier(max_depth=25, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=300, n_jobs=-1, random_state=42)

In [69]:
from catboost import CatBoostClassifier

cat_model = CatBoostClassifier(
    iterations=300,
    depth=8,
    learning_rate=0.05,
    loss_function='MultiClass',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=0
)

cat_model.fit(X_train, y_train)
cat_pred = cat_model.predict(X_test)

CatBoostClassifier(depth=8, eval_metric='Accuracy', iterations=300, learning_rate=0.05, loss_function='MultiClass', random_seed=42, verbose=0)

In [82]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

import pandas as pd

models = {

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        max_depth=25,
        min_samples_split=5,
        min_samples_leaf=2,
        max_features='sqrt',
        random_state=42,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        max_depth=10,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective='multi:softmax',
        num_class=len(set(y_train)),
        eval_metric='mlogloss',
        random_state=42,
        n_jobs=-1
    ),

    "CatBoost": CatBoostClassifier(
        iterations=300,
        depth=8,
        learning_rate=0.05,
        loss_function='MultiClass',
        eval_metric='Accuracy',
        random_seed=42,
        verbose=0
    )
}

# =========================
# RESULTS
# =========================

results = []

# =========================
# TRAIN & EVALUATE
# =========================

from sklearn.metrics import classification_report

for name, model in models.items():

    print(f"\n====================")
    print(f"Training {name}...")
    print(f"====================")

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Overall Metrics
    accuracy = accuracy_score(y_test, y_pred)

    precision = precision_score(
        y_test,
        y_pred,
        average='weighted'
    )

    recall = recall_score(
        y_test,
        y_pred,
        average='weighted'
    )

    f1 = f1_score(
        y_test,
        y_pred,
        average='weighted'
    )

    # Store results
    results.append({
        "Model": name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    })

    # =========================
    # PER CLASS REPORT
    # =========================

    print("\nClassification Report:\n")

    print(classification_report(
        y_test,
        y_pred,
        target_names=le.classes_
    ))
results_df = pd.DataFrame(results)

# Sort by accuracy
results_df = results_df.sort_values(
    by='Accuracy',
    ascending=False
)

print(results_df)

====================
Training Random Forest...
====================

Classification Report:

              precision    recall  f1-score   support

         DoS       1.00      1.00      1.00      9186
       Probe       1.00      1.00      1.00      2331
         R2L       0.97      0.93      0.95       199
         U2R       1.00      0.50      0.67        10
      normal       1.00      1.00      1.00     13469

    accuracy                           1.00     25195
   macro avg       0.99      0.88      0.92     25195
weighted avg       1.00      1.00      1.00     25195


====================
Training XGBoost...
====================

Classification Report:

              precision    recall  f1-score   support

         DoS       1.00      1.00      1.00      9186
       Probe       1.00      1.00      1.00      2331
         R2L       1.00      0.98      0.99       199
         U2R       0.75      0.90      0.82        10
      normal       1.00      1.00      1.00     13469

    accuracy                           1.00     25195
   macro avg       0.95      0.98      0.96     25195
weighted avg       1.00      1.00      1.00     25195


====================
Training CatBoost...
====================

Classification Report:

              precision    recall  f1-score   support

         DoS       1.00      1.00      1.00      9186
       Probe       1.00      0.99      1.00      2331
         R2L       0.98      0.92      0.95       199
         U2R       0.82      0.90      0.86        10
      normal       1.00      1.00      1.00     13469

    accuracy                           1.00     25195
   macro avg       0.96      0.96      0.96     25195
weighted avg       1.00      1.00      1.00     25195

           Model  Accuracy  Precision    Recall  F1 Score
1        XGBoost  0.999087   0.999107  0.999087  0.999093
0  Random Forest  0.998412   0.998404  0.998412  0.998371
2       CatBoost  0.998174   0.998175  0.998174  0.998166

In [71]:
%pip install tensorflow

Requirement already satisfied: tensorflow in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in .\venv\Lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in .\venv\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in .\venv\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in .\venv\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in .\venv\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in .\venv\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in .\venv\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorflow) (2.34.0)
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (from tensorflow) (82.0.1)
Requirement already satisfied: six>=1.12.0 in .\venv\Lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in .\venv\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in .\venv\Lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in .\venv\Lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in .\venv\Lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in .\venv\Lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: numpy>=1.26.0 in .\venv\Lib\site-packages (from tensorflow) (2.4.4)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in .\venv\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in .\venv\Lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.14)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in .\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in .\venv\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in .\venv\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in .\venv\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\venv\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\venv\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in .\venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [83]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
from tensorflow.keras.layers import (
    Input,
    Dense,
    Dropout,
    BatchNormalization
)

from tensorflow.keras.regularizers import l2

input_layer = Input(shape=(X_train.shape[1],))

# Encoder
x = Dense(
    128,
    activation='relu',
    kernel_regularizer=l2(0.0001)
)(input_layer)

x = BatchNormalization()(x)

x = Dropout(0.2)(x)

x = Dense(
    64,
    activation='relu'
)(x)

x = BatchNormalization()(x)

x = Dropout(0.2)(x)

x = Dense(
    32,
    activation='relu'
)(x)

# Bottleneck
latent = Dense(
    16,
    activation='relu'
)(x)

# Decoder
x = Dense(
    32,
    activation='relu'
)(latent)

x = Dense(
    64,
    activation='relu'
)(x)

x = Dense(
    128,
    activation='relu'
)(x)

output_layer = Dense(
    X_train.shape[1],
    activation='linear'
)(x)

In [87]:
# =========================================================
# IMPROVED AUTOENCODER + XGBOOST HYBRID IDS
# FOR NSL-KDD
# =========================================================

# =========================================================
# IMPORTS
# =========================================================

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from tensorflow.keras.models import Model

from tensorflow.keras.layers import (
    Input,
    Dense,
    Dropout,
    BatchNormalization
)

from tensorflow.keras.optimizers import Adam

from tensorflow.keras.regularizers import l2

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau
)

from xgboost import XGBClassifier

# =========================================================
# STANDARD SCALE FOR DEEP LEARNING
# =========================================================

dl_scaler = StandardScaler()

X_train_dl = dl_scaler.fit_transform(X_train)

X_test_dl = dl_scaler.transform(X_test)

# =========================================================
# BUILD AUTOENCODER
# =========================================================

input_dim = X_train_dl.shape[1]

input_layer = Input(shape=(input_dim,))

# =========================================================
# ENCODER
# =========================================================

x = Dense(
    256,
    activation='relu',
    kernel_regularizer=l2(0.0001)
)(input_layer)

x = BatchNormalization()(x)

x = Dropout(0.2)(x)

x = Dense(
    128,
    activation='relu'
)(x)

x = BatchNormalization()(x)

x = Dropout(0.2)(x)

x = Dense(
    64,
    activation='relu'
)(x)

x = BatchNormalization()(x)

# =========================================================
# LATENT SPACE
# =========================================================

latent = Dense(
    32,
    activation='relu',
    name='latent_space'
)(x)

# =========================================================
# DECODER
# =========================================================

x = Dense(
    64,
    activation='relu'
)(latent)

x = Dense(
    128,
    activation='relu'
)(x)

x = Dense(
    256,
    activation='relu'
)(x)

output_layer = Dense(
    input_dim,
    activation='linear'
)(x)

# =========================================================
# CREATE MODELS
# =========================================================

autoencoder = Model(
    inputs=input_layer,
    outputs=output_layer
)

encoder = Model(
    inputs=input_layer,
    outputs=latent
)

# =========================================================
# COMPILE
# =========================================================

autoencoder.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mae',
    metrics=['mse']
)

# =========================================================
# CALLBACKS
# =========================================================

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=5,
    verbose=1
)

# =========================================================
# TRAIN AUTOENCODER
# =========================================================

history = autoencoder.fit(
    X_train_dl,
    X_train_dl,
    epochs=100,
    batch_size=256,
    validation_split=0.2,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# =========================================================
# EXTRACT LATENT FEATURES
# =========================================================

X_train_encoded = encoder.predict(X_train_dl)

X_test_encoded = encoder.predict(X_test_dl)

print("Encoded Train Shape:", X_train_encoded.shape)
print("Encoded Test Shape:", X_test_encoded.shape)

# =========================================================
# COMBINE ORIGINAL + LATENT FEATURES
# =========================================================

X_train_hybrid = np.concatenate(
    [X_train_dl, X_train_encoded],
    axis=1
)

X_test_hybrid = np.concatenate(
    [X_test_dl, X_test_encoded],
    axis=1
)

print("Hybrid Train Shape:", X_train_hybrid.shape)
print("Hybrid Test Shape:", X_test_hybrid.shape)

# =========================================================
# XGBOOST HYBRID MODEL
# =========================================================

xgb_hybrid = XGBClassifier(
    n_estimators=500,
    max_depth=12,
    learning_rate=0.03,
    subsample=0.9,
    colsample_bytree=0.9,
    gamma=0.1,
    min_child_weight=1,
    reg_lambda=1,
    objective='multi:softprob',
    num_class=len(set(y_train)),
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

# =========================================================
# TRAIN XGBOOST
# =========================================================

xgb_hybrid.fit(
    X_train_hybrid,
    y_train
)

# =========================================================
# PREDICT
# =========================================================

y_pred_hybrid = xgb_hybrid.predict(
    X_test_hybrid
)

# =========================================================
# METRICS
# =========================================================

accuracy = accuracy_score(
    y_test,
    y_pred_hybrid
)

precision = precision_score(
    y_test,
    y_pred_hybrid,
    average='weighted'
)

recall = recall_score(
    y_test,
    y_pred_hybrid,
    average='weighted'
)

f1 = f1_score(
    y_test,
    y_pred_hybrid,
    average='weighted'
)

# =========================================================
# RESULTS
# =========================================================

print("\n===================================")
print("AUTOENCODER + XGBOOST HYBRID")
print("===================================")

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

# =========================================================
# CLASSIFICATION REPORT
# =========================================================

print("\nClassification Report:\n")

print(classification_report(
    y_test,
    y_pred_hybrid,
    target_names=le.classes_
))

# =========================================================
# CONFUSION MATRIX
# =========================================================

cm = confusion_matrix(
    y_test,
    y_pred_hybrid
)

print("\nConfusion Matrix:\n")
print(cm)

Epoch 1/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 13s 15ms/step - loss: 0.1414 - mse: 0.9727 - val_loss: 0.1102 - val_mse: 0.8436 - learning_rate: 0.0010
Epoch 2/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 0.0992 - mse: 0.9089 - val_loss: 0.0920 - val_mse: 0.8158 - learning_rate: 0.0010
Epoch 3/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0912 - mse: 0.8932 - val_loss: 0.0874 - val_mse: 0.8030 - learning_rate: 0.0010
Epoch 4/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0876 - mse: 0.8811 - val_loss: 0.0834 - val_mse: 0.7910 - learning_rate: 0.0010
Epoch 5/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0823 - mse: 0.8648 - val_loss: 0.0767 - val_mse: 0.7688 - learning_rate: 0.0010
Epoch 6/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0757 - mse: 0.8458 - val_loss: 0.0734 - val_mse: 0.7620 - learning_rate: 0.0010
Epoch 7/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0740 - mse: 0.8416 - val_loss: 0.0722 - val_mse: 0.7562 - learning_rate: 0.0010
Epoch 8/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0721 - mse: 0.8319 - val_loss: 0.0688 - val_mse: 0.7401 - learning_rate: 0.0010
Epoch 9/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0685 - mse: 0.8165 - val_loss: 0.0659 - val_mse: 0.7278 - learning_rate: 0.0010
Epoch 10/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0654 - mse: 0.8047 - val_loss: 0.0629 - val_mse: 0.7186 - learning_rate: 0.0010
Epoch 11/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0636 - mse: 0.7979 - val_loss: 0.0623 - val_mse: 0.7134 - learning_rate: 0.0010
Epoch 12/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0622 - mse: 0.7944 - val_loss: 0.0599 - val_mse: 0.7100 - learning_rate: 0.0010
Epoch 13/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0612 - mse: 0.7910 - val_loss: 0.0592 - val_mse: 0.7067 - learning_rate: 0.0010
Epoch 14/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0603 - mse: 0.7878 - val_loss: 0.0584 - val_mse: 0.7036 - learning_rate: 0.0010
Epoch 15/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 0.0596 - mse: 0.7842 - val_loss: 0.0573 - val_mse: 0.6987 - learning_rate: 0.0010
Epoch 16/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0589 - mse: 0.7810 - val_loss: 0.0569 - val_mse: 0.6980 - learning_rate: 0.0010
Epoch 17/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0583 - mse: 0.7800 - val_loss: 0.0567 - val_mse: 0.6971 - learning_rate: 0.0010
Epoch 18/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0580 - mse: 0.7791 - val_loss: 0.0565 - val_mse: 0.6970 - learning_rate: 0.0010
Epoch 19/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0577 - mse: 0.7788 - val_loss: 0.0564 - val_mse: 0.6961 - learning_rate: 0.0010
Epoch 20/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0575 - mse: 0.7780 - val_loss: 0.0560 - val_mse: 0.6956 - learning_rate: 0.0010
Epoch 21/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0571 - mse: 0.7775 - val_loss: 0.0553 - val_mse: 0.6948 - learning_rate: 0.0010
Epoch 22/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0567 - mse: 0.7767 - val_loss: 0.0551 - val_mse: 0.6947 - learning_rate: 0.0010
Epoch 23/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0565 - mse: 0.7759 - val_loss: 0.0547 - val_mse: 0.6934 - learning_rate: 0.0010
Epoch 24/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0561 - mse: 0.7750 - val_loss: 0.0547 - val_mse: 0.6924 - learning_rate: 0.0010
Epoch 25/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0559 - mse: 0.7744 - val_loss: 0.0542 - val_mse: 0.6922 - learning_rate: 0.0010
Epoch 26/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0558 - mse: 0.7740 - val_loss: 0.0542 - val_mse: 0.6910 - learning_rate: 0.0010
Epoch 27/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0555 - mse: 0.7733 - val_loss: 0.0541 - val_mse: 0.6912 - learning_rate: 0.0010
Epoch 28/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0555 - mse: 0.7731 - val_loss: 0.0543 - val_mse: 0.6908 - learning_rate: 0.0010
Epoch 29/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0553 - mse: 0.7726 - val_loss: 0.0539 - val_mse: 0.6906 - learning_rate: 0.0010
Epoch 30/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0552 - mse: 0.7725 - val_loss: 0.0541 - val_mse: 0.6904 - learning_rate: 0.0010
Epoch 31/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0550 - mse: 0.7720 - val_loss: 0.0539 - val_mse: 0.6901 - learning_rate: 0.0010
Epoch 32/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0549 - mse: 0.7717 - val_loss: 0.0536 - val_mse: 0.6893 - learning_rate: 0.0010
Epoch 33/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0548 - mse: 0.7713 - val_loss: 0.0536 - val_mse: 0.6894 - learning_rate: 0.0010
Epoch 34/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0548 - mse: 0.7711 - val_loss: 0.0537 - val_mse: 0.6888 - learning_rate: 0.0010
Epoch 35/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0547 - mse: 0.7703 - val_loss: 0.0536 - val_mse: 0.6882 - learning_rate: 0.0010
Epoch 36/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0545 - mse: 0.7697 - val_loss: 0.0533 - val_mse: 0.6873 - learning_rate: 0.0010
Epoch 37/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0544 - mse: 0.7691 - val_loss: 0.0533 - val_mse: 0.6868 - learning_rate: 0.0010
Epoch 38/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0544 - mse: 0.7684 - val_loss: 0.0533 - val_mse: 0.6861 - learning_rate: 0.0010
Epoch 39/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0544 - mse: 0.7672 - val_loss: 0.0531 - val_mse: 0.6840 - learning_rate: 0.0010
Epoch 40/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0540 - mse: 0.7638 - val_loss: 0.0525 - val_mse: 0.6807 - learning_rate: 0.0010
Epoch 41/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0537 - mse: 0.7627 - val_loss: 0.0524 - val_mse: 0.6809 - learning_rate: 0.0010
Epoch 42/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0537 - mse: 0.7625 - val_loss: 0.0524 - val_mse: 0.6807 - learning_rate: 0.0010
Epoch 43/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0535 - mse: 0.7622 - val_loss: 0.0524 - val_mse: 0.6804 - learning_rate: 0.0010
Epoch 44/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 0.0536 - mse: 0.7624 - val_loss: 0.0522 - val_mse: 0.6802 - learning_rate: 0.0010
Epoch 45/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0535 - mse: 0.7621 - val_loss: 0.0521 - val_mse: 0.6803 - learning_rate: 0.0010
Epoch 46/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0533 - mse: 0.7618 - val_loss: 0.0521 - val_mse: 0.6800 - learning_rate: 0.0010
Epoch 47/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0533 - mse: 0.7618 - val_loss: 0.0522 - val_mse: 0.6798 - learning_rate: 0.0010
Epoch 48/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0531 - mse: 0.7616 - val_loss: 0.0520 - val_mse: 0.6797 - learning_rate: 0.0010
Epoch 49/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0531 - mse: 0.7616 - val_loss: 0.0518 - val_mse: 0.6794 - learning_rate: 0.0010
Epoch 50/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0531 - mse: 0.7616 - val_loss: 0.0522 - val_mse: 0.6796 - learning_rate: 0.0010
Epoch 51/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0530 - mse: 0.7615 - val_loss: 0.0517 - val_mse: 0.6795 - learning_rate: 0.0010
Epoch 52/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0530 - mse: 0.7613 - val_loss: 0.0517 - val_mse: 0.6793 - learning_rate: 0.0010
Epoch 53/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0528 - mse: 0.7612 - val_loss: 0.0518 - val_mse: 0.6793 - learning_rate: 0.0010
Epoch 54/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0528 - mse: 0.7610 - val_loss: 0.0516 - val_mse: 0.6789 - learning_rate: 0.0010
Epoch 55/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0527 - mse: 0.7609 - val_loss: 0.0513 - val_mse: 0.6787 - learning_rate: 0.0010
Epoch 56/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0526 - mse: 0.7607 - val_loss: 0.0513 - val_mse: 0.6790 - learning_rate: 0.0010
Epoch 57/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0525 - mse: 0.7606 - val_loss: 0.0514 - val_mse: 0.6786 - learning_rate: 0.0010
Epoch 58/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0525 - mse: 0.7604 - val_loss: 0.0511 - val_mse: 0.6786 - learning_rate: 0.0010
Epoch 59/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0524 - mse: 0.7605 - val_loss: 0.0513 - val_mse: 0.6785 - learning_rate: 0.0010
Epoch 60/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0524 - mse: 0.7604 - val_loss: 0.0513 - val_mse: 0.6784 - learning_rate: 0.0010
Epoch 61/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0523 - mse: 0.7604 - val_loss: 0.0511 - val_mse: 0.6782 - learning_rate: 0.0010
Epoch 62/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0523 - mse: 0.7603 - val_loss: 0.0510 - val_mse: 0.6783 - learning_rate: 0.0010
Epoch 63/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0522 - mse: 0.7603 - val_loss: 0.0508 - val_mse: 0.6785 - learning_rate: 0.0010
Epoch 64/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0521 - mse: 0.7604 - val_loss: 0.0508 - val_mse: 0.6786 - learning_rate: 0.0010
Epoch 65/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0521 - mse: 0.7603 - val_loss: 0.0505 - val_mse: 0.6779 - learning_rate: 0.0010
Epoch 66/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0520 - mse: 0.7601 - val_loss: 0.0507 - val_mse: 0.6781 - learning_rate: 0.0010
Epoch 67/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0520 - mse: 0.7600 - val_loss: 0.0508 - val_mse: 0.6782 - learning_rate: 0.0010
Epoch 68/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0519 - mse: 0.7599 - val_loss: 0.0506 - val_mse: 0.6782 - learning_rate: 0.0010
Epoch 69/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0519 - mse: 0.7598 - val_loss: 0.0503 - val_mse: 0.6777 - learning_rate: 0.0010
Epoch 70/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0518 - mse: 0.7597 - val_loss: 0.0505 - val_mse: 0.6778 - learning_rate: 0.0010
Epoch 71/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 0.0518 - mse: 0.7597 - val_loss: 0.0505 - val_mse: 0.6778 - learning_rate: 0.0010
Epoch 72/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0518 - mse: 0.7596 - val_loss: 0.0503 - val_mse: 0.6774 - learning_rate: 0.0010
Epoch 73/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0517 - mse: 0.7594 - val_loss: 0.0505 - val_mse: 0.6775 - learning_rate: 0.0010
Epoch 74/100
313/315 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0516 - mse: 0.7364
Epoch 74: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0517 - mse: 0.7594 - val_loss: 0.0504 - val_mse: 0.6767 - learning_rate: 0.0010
Epoch 75/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0508 - mse: 0.7587 - val_loss: 0.0493 - val_mse: 0.6763 - learning_rate: 5.0000e-04
Epoch 76/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0506 - mse: 0.7584 - val_loss: 0.0493 - val_mse: 0.6763 - learning_rate: 5.0000e-04
Epoch 77/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0505 - mse: 0.7582 - val_loss: 0.0492 - val_mse: 0.6760 - learning_rate: 5.0000e-04
Epoch 78/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0504 - mse: 0.7580 - val_loss: 0.0492 - val_mse: 0.6759 - learning_rate: 5.0000e-04
Epoch 79/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0504 - mse: 0.7578 - val_loss: 0.0491 - val_mse: 0.6756 - learning_rate: 5.0000e-04
Epoch 80/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0503 - mse: 0.7577 - val_loss: 0.0489 - val_mse: 0.6756 - learning_rate: 5.0000e-04
Epoch 81/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0503 - mse: 0.7575 - val_loss: 0.0489 - val_mse: 0.6753 - learning_rate: 5.0000e-04
Epoch 82/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0503 - mse: 0.7575 - val_loss: 0.0490 - val_mse: 0.6752 - learning_rate: 5.0000e-04
Epoch 83/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0502 - mse: 0.7573 - val_loss: 0.0491 - val_mse: 0.6752 - learning_rate: 5.0000e-04
Epoch 84/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0502 - mse: 0.7572 - val_loss: 0.0489 - val_mse: 0.6751 - learning_rate: 5.0000e-04
Epoch 85/100
311/315 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0509 - mse: 0.7741
Epoch 85: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0502 - mse: 0.7572 - val_loss: 0.0489 - val_mse: 0.6749 - learning_rate: 5.0000e-04
Epoch 86/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0497 - mse: 0.7569 - val_loss: 0.0482 - val_mse: 0.6748 - learning_rate: 2.5000e-04
Epoch 87/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0496 - mse: 0.7567 - val_loss: 0.0481 - val_mse: 0.6744 - learning_rate: 2.5000e-04
Epoch 88/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0495 - mse: 0.7565 - val_loss: 0.0482 - val_mse: 0.6744 - learning_rate: 2.5000e-04
Epoch 89/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0495 - mse: 0.7563 - val_loss: 0.0480 - val_mse: 0.6742 - learning_rate: 2.5000e-04
Epoch 90/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0494 - mse: 0.7563 - val_loss: 0.0480 - val_mse: 0.6740 - learning_rate: 2.5000e-04
Epoch 91/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0494 - mse: 0.7560 - val_loss: 0.0481 - val_mse: 0.6740 - learning_rate: 2.5000e-04
Epoch 92/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0493 - mse: 0.7559 - val_loss: 0.0479 - val_mse: 0.6738 - learning_rate: 2.5000e-04
Epoch 93/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0493 - mse: 0.7558 - val_loss: 0.0478 - val_mse: 0.6737 - learning_rate: 2.5000e-04
Epoch 94/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0492 - mse: 0.7556 - val_loss: 0.0478 - val_mse: 0.6736 - learning_rate: 2.5000e-04
Epoch 95/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0492 - mse: 0.7556 - val_loss: 0.0478 - val_mse: 0.6735 - learning_rate: 2.5000e-04
Epoch 96/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0491 - mse: 0.7555 - val_loss: 0.0477 - val_mse: 0.6735 - learning_rate: 2.5000e-04
Epoch 97/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0491 - mse: 0.7555 - val_loss: 0.0476 - val_mse: 0.6733 - learning_rate: 2.5000e-04
Epoch 98/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0491 - mse: 0.7554 - val_loss: 0.0477 - val_mse: 0.6734 - learning_rate: 2.5000e-04
Epoch 99/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0491 - mse: 0.7554 - val_loss: 0.0475 - val_mse: 0.6732 - learning_rate: 2.5000e-04
Epoch 100/100
315/315 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 0.0490 - mse: 0.7554 - val_loss: 0.0477 - val_mse: 0.6734 - learning_rate: 2.5000e-04
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
788/788 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
Encoded Train Shape: (100778, 32)
Encoded Test Shape: (25195, 32)
Hybrid Train Shape: (100778, 142)
Hybrid Test Shape: (25195, 142)

===================================
AUTOENCODER + XGBOOST HYBRID
===================================
Accuracy  : 0.9991
Precision : 0.9991
Recall    : 0.9991
F1 Score  : 0.9991

Classification Report:

              precision    recall  f1-score   support

         DoS       1.00      1.00      1.00      9186
       Probe       1.00      1.00      1.00      2331
         R2L       0.99      0.98      0.98       199
         U2R       0.82      0.90      0.86        10
      normal       1.00      1.00      1.00     13469

    accuracy                           1.00     25195
   macro avg       0.96      0.98      0.97     25195
weighted avg       1.00      1.00      1.00     25195


Confusion Matrix:

[[ 9182     0     0     0     4]
 [    0  2327     0     0     4]
 [    0     0   195     0     4]
 [    0     0     0     9     1]
 [    4     1     2     2 13460]]

In [85]:
autoencoder = Model(inputs=input_layer,
                    outputs=output_layer)

encoder = Model(inputs=input_layer,
                outputs=latent)

In [75]:
autoencoder.compile(
    optimizer='adam',
    loss='mse'
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [76]:
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = autoencoder.fit(
    X_train,
    X_train,
    epochs=50,
    batch_size=256,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/50
315/315 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6751304.0000 - val_loss: 2385160.0000
Epoch 2/50
315/315 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6751304.0000 - val_loss: 2385160.0000
Epoch 3/50
315/315 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6751303.0000 - val_loss: 2385160.0000
Epoch 4/50
315/315 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6751306.0000 - val_loss: 2385160.0000
Epoch 5/50
315/315 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6751300.5000 - val_loss: 2385160.0000
Epoch 6/50
315/315 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6751303.0000 - val_loss: 2385160.0000

In [78]:
X_train_encoded = encoder.predict(X_train)

X_test_encoded = encoder.predict(X_test)

3150/3150 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
788/788 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step

In [79]:
from xgboost import XGBClassifier

xgb_hybrid = XGBClassifier(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='multi:softmax',
    num_class=len(set(y_train)),
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

xgb_hybrid.fit(
    X_train_encoded,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1, num_class=5, ...)

In [80]:
y_pred_hybrid = xgb_hybrid.predict(
    X_test_encoded
)

In [81]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:",
      accuracy_score(y_test, y_pred_hybrid))

print(classification_report(
    y_test,
    y_pred_hybrid
))

print(confusion_matrix(
    y_test,
    y_pred_hybrid
))

Accuracy: 0.9885294701329629
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9186
           1       0.97      0.95      0.96      2331
           2       0.94      0.87      0.91       199
           3       0.00      0.00      0.00        10
           4       0.99      0.99      0.99     13469

    accuracy                           0.99     25195
   macro avg       0.78      0.76      0.77     25195
weighted avg       0.99      0.99      0.99     25195

[[ 9157     2     0     0    27]
 [    0  2211     0     0   120]
 [    0     0   174     0    25]
 [    1     0     0     0     9]
 [   17    75    11     2 13364]]